//! The inbound channel: a bank of load-on-demand "slot" addons.
//!
//! WoW addons cannot read files at runtime, but `C_AddOns.LoadAddOn` reads an
//! addon's Lua from disk at the moment it loads. The installer therefore
//! pre-creates `OCWow_S001` … `OCWow_Snnn`, each `## LoadOnDemand: 1` with a
//! single `Inbox.lua`, and the companion writes the current state into every
//! slot on each publish. The addon loads a fresh slot and reads the global it
//! defines; each slot is single-use per UI session, and `/reload` frees them.
//!
//! Cheap readiness signals ride on sound files: `PlaySoundFile` reports whether
//! a file will play, and an empty file will not. The installer pre-creates the
//! signal files empty; the companion fills one in to raise it.

use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

/// Default number of slots.
pub const DEFAULT_SLOTS: u16 = 200;
/// Prefix shared by every slot addon.
pub const SLOT_PREFIX: &str = "OCWow_S";
/// Global the slot files assign.
pub const SLOT_GLOBAL: &str = "OCWow_SlotData";

/// Name of slot `index` (1-based), e.g. `OCWow_S007`.
pub fn slot_name(index: u16) -> String {
    format!("{SLOT_PREFIX}{index:03}")
}

/// Which signal slot a message id maps to.
pub fn slot_for_id(id: u32, slots: u16) -> u16 {
    (((id.saturating_sub(1)) % slots.max(1) as u32) + 1) as u16
}

/// Quote a string as a Lua literal.
fn lua_quote(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 32 || c as u32 == 127 => {
                out.push_str(&format!("\\{:03}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// One chat's latest status, as the addon sees it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Reply {
    pub tab: u8,
    pub request: u32,
    pub status: ReplyStatus,
    pub text: String,
    /// OpenCode session id, so the addon can show it.
    pub session: String,
    /// Permission rules a denied tool would need, for an Allow & retry button.
    pub denied: Vec<String>,
}

/// How far along a reply is.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReplyStatus {
    Working,
    Done,
    Error,
}

impl ReplyStatus {
    fn as_str(self) -> &'static str {
        match self {
            ReplyStatus::Working => "working",
            ReplyStatus::Done => "done",
            ReplyStatus::Error => "error",
        }
    }
}

/// Everything the addon needs in one slot read.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SlotData {
    /// The companion's wall clock, in epoch seconds.
    pub now: u64,
    /// Monotonic publish counter.
    pub seq: u64,
    pub replies: Vec<Reply>,
}

/// Render slot data as the body of an `Inbox.lua`.
pub fn render_slot(data: &SlotData) -> String {
    let mut out = String::with_capacity(256 + data.replies.len() * 128);
    out.push_str("-- generated by the ocw companion; do not edit\n");
    out.push_str(SLOT_GLOBAL);
    out.push_str(" = {\n");
    out.push_str(&format!("\tnow = {},\n", data.now));
    out.push_str(&format!("\tseq = {},\n", data.seq));
    out.push_str("\treplies = {\n");
    for reply in &data.replies {
        out.push_str("\t\t{\n");
        out.push_str(&format!("\t\t\ttab = {},\n", reply.tab));
        out.push_str(&format!("\t\t\trequest = {},\n", reply.request));
        out.push_str(&format!("\t\t\tstatus = {},\n", lua_quote(reply.status.as_str())));
        out.push_str(&format!("\t\t\ttext = {},\n", lua_quote(&reply.text)));
        out.push_str(&format!(
            "\t\t\tsession = {},\n",
            lua_quote(&reply.session)
        ));
        out.push_str("\t\t\tdenied = {");
        for (index, rule) in reply.denied.iter().enumerate() {
            if index > 0 {
                out.push_str(", ");
            }
            out.push_str(&lua_quote(rule));
        }
        out.push_str("},\n");
        out.push_str("\t\t},\n");
    }
    out.push_str("\t},\n");
    out.push_str("}\n");
    out
}

/// A tiny but valid 16-bit PCM WAV, used to raise a signal file.
pub fn valid_wav() -> Vec<u8> {
    let mut out = Vec::with_capacity(46);
    let data: [u8; 2] = [0, 0];
    out.extend_from_slice(b"RIFF");
    out.extend_from_slice(&(36u32 + data.len() as u32).to_le_bytes());
    out.extend_from_slice(b"WAVE");
    out.extend_from_slice(b"fmt ");
    out.extend_from_slice(&16u32.to_le_bytes());
    out.extend_from_slice(&1u16.to_le_bytes()); // PCM
    out.extend_from_slice(&1u16.to_le_bytes()); // mono
    out.extend_from_slice(&8000u32.to_le_bytes()); // sample rate
    out.extend_from_slice(&16000u32.to_le_bytes()); // byte rate
    out.extend_from_slice(&2u16.to_le_bytes()); // block align
    out.extend_from_slice(&16u16.to_le_bytes()); // bits per sample
    out.extend_from_slice(b"data");
    out.extend_from_slice(&(data.len() as u32).to_le_bytes());
    out.extend_from_slice(&data);
    out
}

/// The slot bank and its signal files.
#[derive(Debug, Clone)]
pub struct SlotBank {
    /// The `Interface/AddOns` directory that holds the addon and its slots.
    addons_dir: PathBuf,
    /// The main addon's directory, which holds the signal files.
    addon_dir: PathBuf,
    slots: u16,
}

impl SlotBank {
    /// `addon_dir` is `…/Interface/AddOns/OCWow`; slots are created beside it.
    pub fn new(addon_dir: impl Into<PathBuf>, slots: u16) -> Self {
        let addon_dir = addon_dir.into();
        let addons_dir = addon_dir
            .parent()
            .map(Path::to_path_buf)
            .unwrap_or_else(|| PathBuf::from("."));
        Self {
            addons_dir,
            addon_dir,
            slots,
        }
    }

    pub fn slots(&self) -> u16 {
        self.slots
    }

    pub fn addons_dir(&self) -> &Path {
        &self.addons_dir
    }

    /// Path of the `Inbox.lua` inside slot `index`.
    pub fn slot_path(&self, index: u16) -> PathBuf {
        self.addons_dir
            .join(slot_name(index))
            .join("Inbox.lua")
    }

    /// Whether the slots have been installed.
    pub fn is_installed(&self) -> bool {
        self.slot_path(1).is_file() && self.slot_path(self.slots).is_file()
    }

    /// Create the slot addons and the signal files.
    pub fn install(&self, interface: u32, force: bool) -> Result<InstallReport> {
        let mut created = 0u32;

        for index in 1..=self.slots {
            let dir = self.addons_dir.join(slot_name(index));
            let toc = dir.join(format!("{}.toc", slot_name(index)));
            let inbox = dir.join("Inbox.lua");
            if toc.is_file() && inbox.is_file() && !force {
                continue;
            }
            std::fs::create_dir_all(&dir)
                .with_context(|| format!("creating {}", dir.display()))?;
            std::fs::write(
                &toc,
                format!(
                    "## Interface: {interface}\n## Title: OCWow Slot {index:03}\n\
                     ## LoadOnDemand: 1\n## Notes: transport slot for OCWow; do not enable\n\
                     Inbox.lua\n"
                ),
            )?;
            std::fs::write(&inbox, render_slot(&SlotData::default()))?;
            created += 1;
        }

        // Signal files must exist when the client launches, so create them empty
        // and let the companion fill them in to raise them.
        let mut signals = 0u32;
        for kind in ["sig", "ack"] {
            let dir = self.addon_dir.join(kind);
            std::fs::create_dir_all(&dir)?;
            for index in 1..=self.slots {
                let path = dir.join(format!("{index:03}.wav"));
                if !path.is_file() || force {
                    std::fs::write(&path, [])?;
                    signals += 1;
                }
            }
        }

        // Control pair: the addon checks that an empty file reads as unplayable
        // and a valid one as playable before trusting the channel.
        let ctl = self.addon_dir.join("ctl");
        std::fs::create_dir_all(&ctl)?;
        std::fs::write(ctl.join("empty.wav"), [])?;
        std::fs::write(ctl.join("valid.wav"), valid_wav())?;

        Ok(InstallReport {
            addons_dir: self.addons_dir.clone(),
            slots: self.slots,
            created,
            signals,
        })
    }

    /// Publish slot data to every slot, so whichever the addon loads next is
    /// current.
    pub fn publish(&self, data: &SlotData) -> Result<()> {
        let body = render_slot(data);
        for index in 1..=self.slots {
            let path = self.slot_path(index);
            let temp = path.with_extension("lua.tmp");
            {
                let mut file = std::fs::File::create(&temp)
                    .with_context(|| format!("writing {}", temp.display()))?;
                file.write_all(body.as_bytes())?;
            }
            std::fs::rename(&temp, &path)
                .with_context(|| format!("replacing {}", path.display()))?;
        }
        Ok(())
    }

    /// Raise a signal by filling in its pre-created file.
    pub fn raise(&self, kind: &str, index: u16) -> Result<()> {
        let path = self.addon_dir.join(kind).join(format!("{index:03}.wav"));
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, valid_wav())
            .with_context(|| format!("raising {}", path.display()))?;
        Ok(())
    }

    /// Signal that message `id` has a reply ready.
    pub fn signal_reply(&self, id: u32) -> Result<()> {
        self.raise("sig", slot_for_id(id, self.slots))
    }

    /// Signal that message `id` was received and can leave the strip.
    pub fn signal_ack(&self, id: u32) -> Result<()> {
        self.raise("ack", slot_for_id(id, self.slots))
    }
}

/// Summary returned by [`SlotBank::install`].
#[derive(Debug, Clone)]
pub struct InstallReport {
    pub addons_dir: PathBuf,
    pub slots: u16,
    pub created: u32,
    pub signals: u32,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_bank(name: &str, slots: u16) -> SlotBank {
        let root = std::env::temp_dir().join(format!("ocw-slots-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let addon_dir = root.join("AddOns").join("OCWow");
        std::fs::create_dir_all(&addon_dir).unwrap();
        SlotBank::new(addon_dir, slots)
    }

    #[test]
    fn installs_slots_and_signals() {
        let bank = temp_bank("install", 4);
        let report = bank.install(16001, false).unwrap();
        assert_eq!(report.created, 4);
        assert!(bank.is_installed());

        let toc = bank
            .addons_dir
            .join(slot_name(1))
            .join(format!("{}.toc", slot_name(1)));
        let text = std::fs::read_to_string(&toc).unwrap();
        assert!(text.contains("## LoadOnDemand: 1"));
        assert!(text.contains("Interface: 16001"));

        assert!(bank.addon_dir.join("sig").join("001.wav").is_file());
        assert!(bank.addon_dir.join("ctl").join("valid.wav").is_file());
        assert!(bank.addon_dir.join("ctl").join("empty.wav").is_file());

        let _ = std::fs::remove_dir_all(bank.addons_dir.parent().unwrap());
    }

    #[test]
    fn publishes_to_every_slot() {
        let bank = temp_bank("publish", 3);
        bank.install(16001, false).unwrap();

        let data = SlotData {
            now: 1_700_000_000,
            seq: 7,
            replies: vec![Reply {
                tab: 2,
                request: 5,
                status: ReplyStatus::Done,
                text: "hello \"world\"\nsecond line".to_string(),
                session: "ses_abc".to_string(),
                denied: vec!["Bash(rm:*)".to_string()],
            }],
        };
        bank.publish(&data).unwrap();

        for index in 1..=3 {
            let text = std::fs::read_to_string(bank.slot_path(index)).unwrap();
            assert!(text.contains("OCWow_SlotData"));
            assert!(text.contains("tab = 2"));
            assert!(text.contains("request = 5"));
            assert!(text.contains(r#""done""#));
            // Quotes and newlines must be escaped, not emitted raw.
            assert!(text.contains(r#"hello \"world\"\nsecond line"#));
            assert!(text.contains(r#""Bash(rm:*)""#));
        }

        let _ = std::fs::remove_dir_all(bank.addons_dir.parent().unwrap());
    }

    #[test]
    fn signal_files_start_empty_and_are_raised() {
        let bank = temp_bank("signals", 2);
        bank.install(16001, false).unwrap();
        let path = bank.addon_dir.join("sig").join("002.wav");
        assert_eq!(std::fs::metadata(&path).unwrap().len(), 0);

        bank.signal_reply(2).unwrap();
        assert!(std::fs::metadata(&path).unwrap().len() > 0);
        assert!(valid_wav().starts_with(b"RIFF"));

        let _ = std::fs::remove_dir_all(bank.addons_dir.parent().unwrap());
    }

    #[test]
    fn ids_map_onto_slots() {
        assert_eq!(slot_for_id(1, 200), 1);
        assert_eq!(slot_for_id(200, 200), 200);
        assert_eq!(slot_for_id(201, 200), 1);
        assert_eq!(slot_for_id(0, 200), 1);
    }

    #[test]
    fn quotes_control_characters() {
        assert_eq!(lua_quote("a\u{1}b"), "\"a\\001b\"");
    }
}
